### ISSUE TITLE
update: Audio Player 1.3.1

### ISSUE THREAD

**Issue by Rello** [owncloud/app-approval#18]
`App name: `Audio Player
`new/update:` update
`StoreURL: `https://apps.owncloud.com/content/show.php/Audio+Player?content=174738
`Repo: `https://github.com/Rello/audioplayer
`authors: `@Rello @xraMsamohT
`comments: `Audio player for OC with a quick and simple interface.

- [x]  app:check-code green
- [x]  signed

Changelog:
- fix: handling of temporary scanner files [#68](https://github.com/rello/audioplayer/issues/68)
- fix: simpler analysis of incorrect files in scanner [#57](https://github.com/rello/audioplayer/issues/57)
- fix: album sorted correctly by artist and album [#80](https://github.com/rello/audioplayer/issues/80)
- fix: neutral cover for unknown album [#16](https://github.com/rello/audioplayer/issues/16)
- fix: error message from ID3 editor shown in front-end [#77](https://github.com/rello/audioplayer/issues/77)
- enhancement: occ support for library scan and reset [#72](https://github.com/rello/audioplayer/issues/72)
- enhancement: select a dedicated folder for scanning in personal settings [#79](https://github.com/rello/audioplayer/issues/79)
- enhancement: exclude folders from scanning via .noaudio file [#79](https://github.com/rello/audioplayer/issues/79)
- enhancement: significantly reduce database reads during scanning [#79](https://github.com/rello/audioplayer/issues/79)
- enhancement: cleanup of classes; move from \OC\Files\View to \OCP\Files\IRootFolder [#72](https://github.com/rello/audioplayer/issues/72)

**Comment by Rello** [comment]
@DeepDiver1975 @Kawohl 
can you help?

**Comment by DeepDiver1975** [comment]
@Rello should be fixed now - THX

**Comment by Rello** [comment]
@DeepDiver1975 are you sure? :-)

it still shows Experimental.
the only thing changed is, that I am getting SSL issues when accessing the app store from all my OC installations

`Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate`

**Comment by Rello** [comment]
@DeepDiver1975 
thank you.
I am getting cURL issues in OC.
Seems you updated the SSL? but something is missing in the Chain?
https://www.ssllabs.com/ssltest/analyze.html?d=apps.owncloud.com

**Comment by Rello** [comment]
thanks
